### ISSUE TITLE
Do you have the arxiv version of the paper?

### ISSUE THREAD

**Issue by Gatsby23** [minwoo0611/MA-LIO#1]

**Comment by minwoo0611** [comment]
The specified version has not yet been published on arXiv. We have recently completed the review process, and we anticipate being able to upload the preprint within the next month. Thank you for your inquiry.

Sincerely,
Minwoo Jung

**Comment by Gatsby23** [comment]
> The specified version has not yet been published on arXiv. We have recently completed the review process, and we anticipate being able to upload the preprint within the next month. Thank you for your inquiry.
> 
> Sincerely, Minwoo Jung

Question about the Point-wise. Does it mean using the point-to-point constraint? It means you use the GICP to update the state instead of the original ICP in the FAST-LIO2？

**Comment by minwoo0611** [comment]
In our paper, point-wise means assigning a unique uncertainty to each point. This uncertainty is used in the error state extended Kalman filter, and the measurement model is the same as in FAST-LIO2. In other words, we apply the point-to-plane model used in FAST-LIO2, but you can think of it as an added weight model according to the uncertainty.

**Comment by Gatsby23** [comment]
Thank you for your patient guidance. I hope that your paper will be accepted by the reviewers as soon as possible.
