### ISSUE TITLE
Can I visualize pointcloud RGB color from calibrated camera images?

### ISSUE THREAD

**Issue by SangHunHan92** [minwoo0611/MA-LIO#14]
Hi! Thanks for great work!

I want to get final 3D map with RGB color.
I have calibrated RGB image with Lidar sensor, and I want to add RGB color on 3D map.

Can I do this? And what should I do?

**Comment by minwoo0611** [comment]
Hello, @SangHunHan92 

I recommend you to use [this repository](https://github.com/hku-mars/r3live) which name is R3LIVE.

I hope this comment can help your inquiry.

Thank you :)

**Comment by SangHunHan92** [comment]
Thanks for recommending.
I hope this solves the problem I have.
