### ISSUE TITLE
Question about experiment

### ISSUE THREAD

**Issue by LiuQiir** [minwoo0611/MA-LIO#16]
Thanks for your great work!!!
I would like to reproduce the visualization of your paper about maps with points color-coded by their localization weight. how do I need to change the code?

**Comment by minwoo0611** [comment]
Hello, @LiuQiir.

The exact code for visualization as used in our paper does not exist, but you can still replicate similar results with a few adjustments. Here's what you need to do:

1. Declare a global variable and store the weight variable in h_share_model.
2. Modify the intensity value of the pointcloud in the publish_frame_world function.

These steps will enable you to visualize the localization weight in rviz.

I hope this process can help to solve your problem.

Thank you :)
