### ISSUE TITLE
A mistake?

### ISSUE THREAD

**Issue by h-k8888** [minwoo0611/MA-LIO#27]
https://github.com/minwoo0611/MA-LIO/blob/0e98fcb6b897c14e083abbc340cb54c854b429f8/MA_LIO/include/common_lib.h#L145

The parameter _**plane_cov**_ without **_&_**?

**Comment by minwoo0611** [comment]
Thank you for pointing out this oversight, @h-k8888. You're correct—the `plane_cov` parameter should indeed use a reference (`&`) to pass its value efficiently. We appreciate your attention to detail and will update the function definition to include this change. Thanks again for your valuable contribution!
