### ISSUE TITLE
A Mistake？

### ISSUE THREAD

**Issue by Akina2001** [minwoo0611/MA-LIO#32]
Hello,
Thanks for open sourcing this great work. I have a confusion in the code as follows: 
![1720679880987](https://github.com/minwoo0611/MA-LIO/assets/101882396/0cfb0db8-2cdc-4b5d-bcdc-f36f161f3e55)

Should it be:
 evalPointUncertainty(feats_down_body->points[i], cov, pose_unc[which_lidar][imu_idx]);

**Comment by minwoo0611** [comment]
Hello @Akina2001,

Thank you for finding our mistakes. We have changed it and committed it to the main branch.

It is great that you continuously have attention for our repository and find the mistakes. Your careful attention helps us make our work better and keep our code high quality. We appreciate your contributions and look forward to your continued support.

Best regards.
