### ISSUE TITLE
Running problems on public datasets

### ISSUE THREAD

**Issue by baibai09** [minwoo0611/MA-LIO#5]
Very good work！ 
When I use a single LIDAR, it always crashes. I have tried various solutions to this problem, but none of them have been successful. As a result, I am turning to you for help.

1. LIO-SAM Dataset [walk](https://drive.google.com/drive/folders/1gJHwfdHCRdjP7vuT556pv8atqrCJPbUq)
  The map will drift and the program will crash.
![err10](https://github.com/minwoo0611/MA-LIO/assets/138378838/55622fd0-b466-442f-b953-f0967d775a18)
![err11](https://github.com/minwoo0611/MA-LIO/assets/138378838/800120c4-b1ce-4da1-b681-e6acd085304f)

2. utbm dataset [utbm](https://epan-utbm.github.io/utbm_robocar_dataset/#Downloads)
The program just crashes
![err09](https://github.com/minwoo0611/MA-LIO/assets/138378838/cba030c5-e1c8-41e9-9fcd-b926ee435922)

**Comment by minwoo0611** [comment]
Dear @baibai09,

Firstly, thank you for testing MA-LIO.
I find that a bit more information would greatly assist me in fully understanding and addressing the issue at hand.

Could you elaborate on how you have modified the code to accommodate different datasets? 

Resolving the issue using solely the image you shared presents a significant challenge. Additional related materials, such as snippets of your code change, would be highly beneficial in facilitating a more efficient and accurate troubleshooting process.

Additionally, I have not yet executed tests using the UTBM dataset. Nonetheless, the LIO-SAM walking dataset is functioning without any issues when interfaced with the MA-LIO system.

![Screenshot from 2023-07-03 07-01-54](https://github.com/minwoo0611/MA-LIO/assets/57853087/28cfe523-cf75-4111-98ee-7df0a8d2342c)

![Screenshot from 2023-07-03 07-02-11](https://github.com/minwoo0611/MA-LIO/assets/57853087/fa2434ab-9e69-4b88-aba1-5df9fd39d974)

**Comment by baibai09** [comment]
Thank you very much for your reply!

Here are some of my configuration changes and the code：
Is it because I'm using Ubuntu 18.04, not Ubuntu 20.04?

![err14](https://github.com/minwoo0611/MA-LIO/assets/138378838/f2d29a27-3e3b-4bd2-84fc-2cd12a039254)
![err10](https://github.com/minwoo0611/MA-LIO/assets/138378838/2061350c-f61b-4fb8-bdfc-496563848b07)
![err11](https://github.com/minwoo0611/MA-LIO/assets/138378838/7d0ee222-c10c-4668-b79f-ee07ff2b2cd9)
![err12](https://github.com/minwoo0611/MA-LIO/assets/138378838/dc1a60c7-d171-4586-8eb4-b1052cfc3c1f)

**Comment by minwoo0611** [comment]
Thank you for sharing your code!

The things you change are all correct!
However, the extrinsic between LiDAR and IMU seems be false.

When we see the config.yaml of LIO-SAM, the extrinsic between two sensors is  [-1, 0, 0, 0, 1, 0, 0, 0, -1].
In LIO-SAM, extrinsic calibration is defined as IMU to LiDAR; however, our definitions is LiDAR to IMU (In fact, it does not a problem in the problem as the inverse of extrinsic is sams) with the form of quaterion [qw, qx, qy, qz].
Therefore, the extrinsic_R in yaml file should be changed as [0, 0, 1, 0].

I hope that this answer can solve you problem.

**Comment by baibai09** [comment]
Thank you for your assistance. Unfortunately, the issue persists even after I changed the external reference. I will continue to investigate the problem. 
Thank you again for your response.
